"""added school_classes table

Revision ID: adc86cd3210e
Revises: f85fd4bb2417
Create Date: 2026-02-09 13:55:05.325770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc86cd3210e'
down_revision = 'f85fd4bb2417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_users_school_classes', 'school_classes', ['class_id'], ['class_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_school_classes', type_='foreignkey')
        batch_op.drop_column('class_id')

    op.create_table('_alembic_tmp_users',
    sa.Column('user_id', sa.BLOB(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login_at', sa.DATETIME(), nullable=True),
    sa.Column('class_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.class_id'], name=op.f('fk_users_school_classes')),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
